"""Company interview profiles.

Each company has:
- style: injected into the interviewer system prompt (drives real-Claude behavior)
- focus: topic emphases woven into the style line
- questions: signature questions asked verbatim by the offline mock interviewer
  (interleaved with the topic question bank), and representative of the
  company's real interview themes.
"""


def _c(style: str, focus: list[str], questions: list[str]) -> dict:
    return {"style": style, "focus": focus, "questions": questions}


COMPANIES: dict[str, dict] = {
    # ---- Big Tech ----
    "Google": _c(
        "Googleyness style: algorithmic depth, complexity analysis, clean abstractions; always ask 'why' after a correct answer.",
        ["Data Structures & Algorithms", "System Design"],
        ["How would you design the ranking pipeline for search autocomplete serving billions of queries a day?",
         "You need to detect near-duplicate web pages across the whole index. Walk me through your approach and its complexity."]),
    "Meta": _c(
        "Meta style: fast execution, product sense plus strong coding; expects two solved problems in 35 minutes with clean code first try.",
        ["Data Structures & Algorithms", "React"],
        ["Design the news-feed ranking system — how do you trade engagement against freshness at billions of reads?",
         "Given a stream of friend-connection events, how do you compute mutual-friend counts efficiently?"]),
    "Amazon": _c(
        "Amazon bar-raiser style: Leadership Principles (Ownership, Dive Deep, Customer Obsession) woven into technical follow-ups; demands data and metrics.",
        ["System Design", "Behavioral"],
        ["Tell me about a time you disagreed with your manager and committed anyway — what was the measurable outcome?",
         "Design the inventory service for a marketplace where overselling a single unit costs real money."]),
    "Microsoft": _c(
        "Microsoft style: practical problem solving, collaboration signals, growth mindset; builds problems up in stages.",
        ["C++", "System Design"],
        ["Design the sync engine for a OneDrive-like service handling offline edits and conflicts.",
         "How would you debug a Windows service whose memory grows 1% per hour in production?"]),
    "Apple": _c(
        "Apple style: deep ownership of the stack, attention to detail, performance and battery/memory constraints; secretive, expects precision.",
        ["C++", "Operating Systems"],
        ["Your animation stutters at 120Hz on one device model only. Walk me through the investigation.",
         "How would you design an API that must never break backward compatibility for a decade?"]),
    "Netflix": _c(
        "Netflix style: senior-level autonomy, distributed-systems depth, candid direct tone; expects strong opinions loosely held.",
        ["System Design", "AWS"],
        ["Design the video CDN selection logic when a whole AWS region degrades during peak hours.",
         "How would you A/B test a change to the playback buffering algorithm without hurting members?"]),
    "Nvidia": _c(
        "Nvidia style: performance-first thinking, parallelism, memory hierarchies; expects mechanical sympathy with hardware.",
        ["C++", "Operating Systems"],
        ["Explain how you'd restructure a memory-bound loop to exploit cache locality and SIMD.",
         "When does moving a workload to the GPU make it slower? Give concrete conditions."]),
    "Tesla": _c(
        "Tesla style: first-principles reasoning, hard deadlines, safety-critical code; expects hands-on debugging war stories.",
        ["C++", "Operating Systems"],
        ["A firmware update causes intermittent sensor dropouts in 0.1% of vehicles. How do you find it?",
         "Design the over-the-air update system so a failed update can never brick a car."]),

    # ---- Product / SaaS ----
    "Stripe": _c(
        "Stripe style: API design excellence, correctness with money, meticulous edge-case handling; practical coding over puzzles.",
        ["System Design", "SQL"],
        ["Design an idempotent payments API — what exactly makes a retry safe?",
         "A customer was double-charged once in 10 million transactions. How do you find the bug and make it impossible?"]),
    "Airbnb": _c(
        "Airbnb style: product-minded engineering, cross-functional empathy, practical coding on realistic data.",
        ["System Design", "React"],
        ["Design the search-and-availability system where hosts edit calendars while guests are booking.",
         "How would you prevent double-booking across two simultaneous checkouts of the same listing?"]),
    "LinkedIn": _c(
        "LinkedIn style: scale-focused backend questions plus craftsmanship; expects clean layered design.",
        ["Java", "System Design"],
        ["Design the 'people you may know' graph computation for 900M members.",
         "How would you page through a member's connections API consistently while the graph mutates?"]),
    "X (Twitter)": _c(
        "X style: real-time systems, fan-out strategies, pragmatic engineering under load.",
        ["System Design", "Data Structures & Algorithms"],
        ["Design tweet fan-out: when do you push to timelines versus pull at read time?",
         "How do you count trending hashtags over a sliding 10-minute window at firehose scale?"]),
    "Snap": _c("Snap style: mobile-first performance, ephemeral data handling, camera pipelines.",
        ["System Design", "Operating Systems"],
        ["Design disappearing messages so 'deleted' actually means deleted — where are all the copies?",
         "How would you keep camera-to-screen latency under 100ms on low-end Android devices?"]),
    "Pinterest": _c("Pinterest style: recommendation systems and visual search; pragmatic ML-adjacent engineering.",
        ["System Design", "Python"],
        ["Design the home-feed recommender combining fresh pins with proven engagers.",
         "How do you deduplicate visually near-identical images at upload time?"]),
    "Spotify": _c("Spotify style: autonomous squads, streaming infrastructure, data-driven product thinking.",
        ["System Design", "Java"],
        ["Design Discover Weekly: batch or streaming, and where does personalization happen?",
         "How would you make audio start in under 200ms globally on flaky mobile networks?"]),
    "Shopify": _c("Shopify style: pragmatic full-stack craftsmanship, flash-sale scale, merchant empathy.",
        ["System Design", "SQL"],
        ["Design checkout to survive a flash sale doing 100x normal traffic for exactly 10 minutes.",
         "A merchant's storefront is slow only on Tuesdays. Debug it end to end."]),
    "Block (Square)": _c("Block style: payments correctness, offline-first point-of-sale, careful API design.",
        ["System Design", "Java"],
        ["Design a card reader that accepts payments offline — how do you bound fraud risk?",
         "Walk me through exactly-once semantics for a payment ledger under retries."]),
    "PayPal": _c("PayPal style: transaction integrity, fraud/risk systems, service reliability.",
        ["Java", "SQL"],
        ["Design the double-entry ledger for transfers between accounts in different currencies.",
         "How would you detect account-takeover fraud in real time without blocking good users?"]),
    "Salesforce": _c("Salesforce style: platform thinking, multi-tenancy, API contracts, customer scenarios.",
        ["Java", "System Design"],
        ["Design row-level security in a multi-tenant database shared by 100k organizations.",
         "One tenant's workload is degrading others. How do you find and isolate it?"]),
    "Adobe": _c("Adobe style: strong CS fundamentals plus product sense; expects crisp definitions.",
        ["C++", "Data Structures & Algorithms"],
        ["Design the undo/redo system for a document editor with collaborative editing.",
         "How would you represent and render a 100k-layer composition efficiently?"]),
    "Atlassian": _c("Atlassian style: collaborative tone, code quality, API design, real-world scenarios.",
        ["Java", "System Design"],
        ["Design Jira's permission model so checking 'can user X see issue Y' is O(1)-ish.",
         "How would you migrate a monolith's hottest endpoint to a service with zero downtime?"]),
    "ServiceNow": _c("ServiceNow style: enterprise workflow platforms, Java depth, upgrade safety.",
        ["Java", "SQL"],
        ["Design a workflow engine where customers define arbitrary approval chains.",
         "How do you upgrade a platform running customer-written scripts without breaking them?"]),
    "Workday": _c("Workday style: correctness in HR/finance data, object modeling, careful migrations.",
        ["Java", "DBMS"],
        ["Model an org chart that supports time-travel queries: 'who reported to whom last March?'",
         "Design a payroll calculation pipeline that must be exactly right and auditable."]),
    "SAP": _c("SAP style: enterprise data modeling, integration patterns, methodical fundamentals.",
        ["SQL", "DBMS"],
        ["Design the data model for a purchase-order approval system with country-specific rules.",
         "How would you sync master data across 12 regional ERP instances?"]),
    "Oracle": _c("Oracle style: heavy on SQL, database internals, memory management, precise language semantics.",
        ["SQL", "DBMS"],
        ["Explain how MVCC lets readers never block writers — and what it costs.",
         "A query plan flipped overnight and latency went 50x. What happened and how do you fix it?"]),
    "IBM": _c("IBM style: fundamentals, enterprise integration, methodical structured interviews.",
        ["Java", "Operating Systems"],
        ["Design a message bridge between a mainframe batch system and a Kafka-based platform.",
         "Explain how you'd containerize a legacy app that writes to local disk and assumes root."]),
    "Intel": _c("Intel style: systems programming, hardware-software boundary, performance measurement.",
        ["C++", "Operating Systems"],
        ["What actually happens, cycle by cycle, on a branch mispredict — and how do you write code to avoid them?",
         "Design a lock-free single-producer single-consumer ring buffer."]),
    "Qualcomm": _c("Qualcomm style: embedded systems, power constraints, C/C++ depth.",
        ["C++", "Operating Systems"],
        ["Your interrupt handler occasionally misses deadlines. How do you diagnose it?",
         "Design a driver-level power-management state machine for a modem chip."]),
    "Cisco": _c("Cisco style: networking depth, protocols, systems troubleshooting.",
        ["Networking", "Operating Systems"],
        ["Packets are dropping between two datacenters but only for large payloads. Debug it layer by layer.",
         "Design a rate limiter that runs inside a router's data plane."]),
    "VMware": _c("VMware style: virtualization internals, OS depth, distributed control planes.",
        ["Operating Systems", "C++"],
        ["Explain what makes live VM migration possible — what state moves and when?",
         "How does a hypervisor keep one guest from starving others of CPU?"]),
    "Red Hat": _c("Red Hat style: Linux internals, open-source collaboration, containers and Kubernetes.",
        ["Operating Systems", "Docker"],
        ["Walk me through what happens in the kernel when a container hits its memory limit.",
         "Design an operator that safely automates a stateful database on Kubernetes."]),
    "Zoom": _c("Zoom style: real-time media, reliability under bad networks, pragmatic scaling.",
        ["Networking", "System Design"],
        ["Design the audio path to stay usable at 40% packet loss.",
         "How do you place media servers so a global meeting minimizes worst-case latency?"]),
    "Dropbox": _c("Dropbox style: sync correctness, storage systems, careful concurrency.",
        ["System Design", "Python"],
        ["Design file sync when the same file is edited on two offline laptops.",
         "How would you dedupe petabytes of user files without leaking data across accounts?"]),
    "Cloudflare": _c("Cloudflare style: edge computing, networking depth, performance at global scale.",
        ["Networking", "System Design"],
        ["Design a DDoS mitigation layer that distinguishes a flash crowd from an attack.",
         "How would you run customer code safely at the edge in under 5ms of overhead?"]),
    "Twilio": _c("Twilio style: developer-first APIs, messaging infrastructure, delivery guarantees.",
        ["System Design", "Node.js"],
        ["Design an SMS API with per-country carrier quirks and strict rate limits.",
         "How do you guarantee webhook delivery to flaky customer endpoints?"]),
    "Datadog": _c("Datadog style: high-throughput ingestion, time-series storage, observability depth.",
        ["System Design", "Data Structures & Algorithms"],
        ["Design ingestion for 10M metrics per second with 1-second query freshness.",
         "How would you store and query high-cardinality tags efficiently?"]),
    "Palantir": _c("Palantir style: decomposition of messy real-world problems, strong CS under ambiguity.",
        ["Data Structures & Algorithms", "System Design"],
        ["You get 500 heterogeneous CSV feeds that must join into one entity graph. Where do you start?",
         "Design an access-control system for data where need-to-know changes daily."]),
    "Databricks": _c("Databricks style: distributed data processing, JVM performance, systems depth.",
        ["System Design", "Java"],
        ["Explain how a shuffle works in a distributed query engine and why it dominates cost.",
         "Design speculative execution for straggler tasks without wasting the cluster."]),
    "Snowflake": _c("Snowflake style: database internals, separation of storage and compute, SQL depth.",
        ["DBMS", "SQL"],
        ["Why does separating storage from compute change how you cache? Design the cache layers.",
         "Design time-travel queries: SELECT ... AT (TIMESTAMP => ...) — what does storage look like?"]),

    # ---- Finance / Quant ----
    "Goldman Sachs": _c(
        "Goldman Sachs style: puzzles, probability, low-level details (memory, threading), formal tone, pressure-tests precision.",
        ["Java", "Data Structures & Algorithms"],
        ["You flip a fair coin until you see heads-tails. What's the expected number of flips? Now code the simulation.",
         "Two threads increment a shared counter 1M times each and the result is wrong. Explain every fix you know."]),
    "JP Morgan": _c("JP Morgan style: core Java/SQL depth, correctness under constraints, formal tone.",
        ["Java", "SQL"],
        ["Design an end-of-day reconciliation job that must finish inside a 2-hour window, or else.",
         "Explain exactly what happens when two transactions deadlock — and how you'd prevent it in a payments schema."]),
    "Morgan Stanley": _c("Morgan Stanley style: solid CS fundamentals, threading, careful precise answers.",
        ["Java", "C++"],
        ["Implement a thread-safe bounded blocking queue from primitives — no library classes.",
         "Why is floating point dangerous for money, and what do you use instead?"]),
    "Bloomberg": _c("Bloomberg style: C++ and data structures on real market-data problems, fast practical coding.",
        ["C++", "Data Structures & Algorithms"],
        ["Design the data structure for a real-time order book with O(1) best-bid access.",
         "You receive out-of-order timestamped ticks. Produce a correct consolidated feed."]),
    "Citadel": _c("Citadel style: extreme performance awareness, probability, low-latency systems.",
        ["C++", "Data Structures & Algorithms"],
        ["Your strategy's p99 latency doubled after a 'harmless' refactor. Find it — the profiler shows nothing.",
         "Estimate: how many cache misses can you afford in a 2-microsecond trading decision?"]),
    "Two Sigma": _c("Two Sigma style: strong math/probability plus clean engineering; data pipeline rigor.",
        ["Python", "Data Structures & Algorithms"],
        ["You backtest a strategy and it looks great. List every way the backtest could be lying to you.",
         "Design a point-in-time-correct feature store for market data."]),
    "Jane Street": _c("Jane Street style: probability puzzles, expected-value reasoning, functional thinking.",
        ["Data Structures & Algorithms", "OOP"],
        ["I roll a die; you can take the value or roll again (up to 3 rolls total). What's your strategy and its EV?",
         "Design an immutable data structure for an order book — why might immutability win here?"]),
    "DE Shaw": _c("DE Shaw style: rigorous CS fundamentals, math, careful complexity analysis.",
        ["Data Structures & Algorithms", "C++"],
        ["Given a stream of numbers, maintain the median with optimal complexity. Now make it distributed.",
         "Prove your solution's complexity bound — then break your own proof."]),
    "American Express": _c("American Express style: Java services, fraud/risk scenarios, steady fundamentals.",
        ["Java", "SQL"],
        ["Design the authorization decision service: 150ms budget including a fraud model call.",
         "How do you evolve a database schema used by 40 services without a big-bang release?"]),
    "Visa": _c("Visa style: transaction processing at massive scale, reliability engineering.",
        ["Java", "System Design"],
        ["VisaNet processes 65k transactions/second. Design the deduplication layer for retried authorizations.",
         "What does five-nines availability actually require of your deployment and data tier?"]),
    "Mastercard": _c("Mastercard style: payment networks, batch + real-time coexistence, careful APIs.",
        ["Java", "System Design"],
        ["Design settlement between 20k banks: real-time authorization, end-of-day netting.",
         "A clearing file arrives corrupted at 2am. Design the pipeline so this is a non-event."]),

    # ---- Marketplaces / Consumer ----
    "Uber": _c("Uber style: scale and real-time systems; pushes on edge cases and geo-data scenarios.",
        ["System Design", "Data Structures & Algorithms"],
        ["Design driver-rider matching in a dense city — what's your spatial index and why?",
         "Surge pricing needs supply/demand per hexagon in near-real-time. Build the pipeline."]),
    "Lyft": _c("Lyft style: practical distributed systems, geo problems, collaborative tone.",
        ["System Design", "Python"],
        ["Design ETA prediction serving: how fresh do features need to be, and how do you keep them fresh?",
         "How would you shard trip data: by city, by rider, or by time? Defend it."]),
    "DoorDash": _c("DoorDash style: logistics optimization, three-sided marketplace, practical engineering.",
        ["System Design", "Data Structures & Algorithms"],
        ["Design dasher assignment when a restaurant is running 20 minutes behind.",
         "Batching two orders per dasher: when does it help, and how do you decide in real time?"]),
    "Instacart": _c("Instacart style: inventory uncertainty, marketplace logistics, pragmatic full-stack.",
        ["System Design", "SQL"],
        ["The catalog says in-stock but the shelf is empty 8% of the time. Design around that uncertainty.",
         "Design shopper routing inside a store you've never mapped."]),
    "Airtel/Telecom": _c("Telecom style: high-volume messaging, billing correctness, network-adjacent systems.",
        ["Java", "Networking"],
        ["Design a prepaid balance system where race conditions literally give away free calls.",
         "How would you detect SIM-box fraud from call-detail records?"]),
    "Coinbase": _c("Coinbase style: security-first, financial correctness, blockchain fundamentals.",
        ["System Design", "Security"],
        ["Design hot-wallet architecture: what stays online, what never does, and how do funds move?",
         "How do you credit a deposit exactly once given blockchain reorgs?"]),
    "Robinhood": _c("Robinhood style: real-time market data, reliability during volatility spikes.",
        ["System Design", "Java"],
        ["Design the order-entry path to degrade gracefully when volume goes 30x in a minute.",
         "Users see stale portfolio values during market open. Find the bottleneck."]),

    # ---- India tech ----
    "Flipkart": _c("Flipkart style: e-commerce scale (Big Billion Days), DSA rigor, system design depth.",
        ["Data Structures & Algorithms", "System Design"],
        ["Design flash-sale inventory for 1M units and 50M interested buyers.",
         "Design the seller-side pricing engine that reacts to competitor changes within minutes."]),
    "Swiggy": _c("Swiggy style: hyperlocal logistics, real-time tracking, pragmatic scaling.",
        ["System Design", "Java"],
        ["Design live order tracking for 500k concurrent orders with 5-second freshness.",
         "Rider allocation during rain: demand doubles, supply halves. What changes in your matcher?"]),
    "Zomato": _c("Zomato style: consumer scale, search and discovery, cost-conscious infrastructure.",
        ["System Design", "SQL"],
        ["Design restaurant search with geo, cuisine, rating and 'open now' filters at city scale.",
         "How would you cut your cloud bill 30% without hurting p99 latency?"]),
    "Paytm": _c("Paytm style: payments and wallets, UPI-scale traffic, correctness with money.",
        ["Java", "System Design"],
        ["Design UPI payment flows that survive bank-side timeouts without double-debits.",
         "Reconcile 100M wallet transactions daily against bank statements — design the pipeline."]),
    "PhonePe": _c("PhonePe style: UPI scale (billions/month), low-latency services, strong DSA screen.",
        ["Data Structures & Algorithms", "System Design"],
        ["A UPI transaction shows debited-but-not-credited. Walk through the exact state machine and recovery.",
         "Design idempotency across three parties: payer bank, NPCI switch, and payee bank."]),
    "Razorpay": _c("Razorpay style: payment gateways, API-first design, webhooks and retries done right.",
        ["Node.js", "System Design"],
        ["Design payment-gateway routing that fails over between bank processors mid-transaction.",
         "Your webhook consumers are slow and your queue is growing. What's your backpressure story?"]),
    "CRED": _c("CRED style: polished product engineering, high code-quality bar, fintech correctness.",
        ["Java", "React"],
        ["Design credit-card bill-fetch across 40 banks with wildly different interfaces.",
         "How do you keep a rewards ledger consistent when a payment is refunded a week later?"]),
    "Zerodha": _c("Zerodha style: lean engineering, market data at scale, minimal-dependency systems.",
        ["Python", "System Design"],
        ["Design the order management system for 10M orders on a budget of three servers. Seriously.",
         "Market opens and one instrument gets 100k orders/second. What's your admission control?"]),
    "Ola": _c("Ola style: geo-scale matching, India-specific network conditions, pragmatic choices.",
        ["System Design", "Java"],
        ["Design ride matching that works when driver phones drop GPS for 30-second stretches.",
         "How do you price intercity rides where return-trip probability matters?"]),
    "Freshworks": _c("Freshworks style: SaaS multi-tenancy, Ruby/Java services, customer-scale pragmatism.",
        ["System Design", "SQL"],
        ["Design a shared-schema multi-tenant CRM — where do you draw the isolation line?",
         "One tenant imports 5M contacts at noon. Protect everyone else."]),

    # ---- Services / Consulting ----
    "TCS": _c("TCS style: fundamentals, syntax fluency, definitions, standard patterns; methodical coverage.",
        ["Java", "SQL"],
        ["Explain the difference between an abstract class and an interface with a real example you'd write.",
         "Write a SQL query to find the second-highest salary per department — then explain its plan."]),
    "Infosys": _c("Infosys style: CS fundamentals, OOP clarity, structured problem-solving, aptitude flavor.",
        ["OOP", "SQL"],
        ["Walk me through the four pillars of OOP with one code example each — no textbook definitions.",
         "Normalize this messy orders table to 3NF and tell me when you'd deliberately stop at 2NF."]),
    "Wipro": _c("Wipro style: language fundamentals, basic DSA, database queries, steady methodical questioning.",
        ["Java", "Data Structures & Algorithms"],
        ["Reverse a linked list on the whiteboard, then tell me its complexity and one real use.",
         "Explain exception handling in Java: checked vs unchecked, with a case where each is right."]),
    "HCLTech": _c("HCLTech style: practical maintenance scenarios, debugging, fundamentals over puzzles.",
        ["Java", "SQL"],
        ["You inherit a 10-year-old codebase with no tests. Your first three moves?",
         "A nightly batch job that took 1 hour now takes 6. Diagnose it."]),
    "Accenture": _c("Accenture style: client scenarios, communication, breadth across stack and cloud basics.",
        ["CI/CD", "AWS"],
        ["A client wants to move a legacy app to the cloud in 3 months. Sketch your assessment week.",
         "Explain blue-green deployment to a non-technical client stakeholder."]),
    "Cognizant": _c("Cognizant style: fundamentals, SDLC knowledge, practical coding, team scenarios.",
        ["Java", "SQL"],
        ["Explain the SDLC of your last project and where quality actually got enforced.",
         "Given two tables, employees and departments, write the query for departments with no employees."]),
    "Capgemini": _c("Capgemini style: aptitude plus fundamentals, pseudo-code comfort, client communication.",
        ["OOP", "SQL"],
        ["Write pseudo-code to detect a duplicate in an unsorted array, then improve it twice.",
         "What's a foreign key, really — and what breaks when you disable the constraint for a load job?"]),
    "Service-Based": _c("Generic service company style: fundamentals, syntax fluency, definitions, standard patterns.",
        ["Java", "SQL"],
        ["Explain method overloading vs overriding with examples from code you've written.",
         "What are indexes and when do they hurt more than help?"]),
    "Startup": _c("Startup style: pragmatic breadth — shipping speed, debugging skill, full-stack versatility; informal but sharp.",
        ["JavaScript", "System Design"],
        ["It's launch day, the site is down, and the error is 'connection pool exhausted'. Go.",
         "You have two weeks to build payments, auth, and admin. What do you buy vs build?"]),
}


def company_names() -> list[str]:
    return list(COMPANIES.keys())


def company_blurb(name: str) -> str:
    style = COMPANIES[name]["style"]
    first_sentence = style.split(";")[0].split(". ")[0].rstrip(".")
    return first_sentence + "."


def company_style_prompt(name: str) -> str:
    """Full style line for the interviewer system prompt."""
    company = COMPANIES.get(name)
    if not company:
        return ""
    focus = ", ".join(company["focus"])
    return f"{company['style']} Emphasize these areas: {focus}."


def signature_questions(name: str) -> list[str]:
    return COMPANIES.get(name, {}).get("questions", [])
