"""Topic-specific technical question bank for offline (mock) mode.

Questions are generated from a concept matrix: ~12 core concepts per topic
crossed with 5 question styles per difficulty tier. That yields 60 distinct
questions per (topic, difficulty) — 180 per topic — while every question stays
genuinely about the chosen topic.

With a real ANTHROPIC_API_KEY the interviewer chain generates unlimited
questions dynamically; this bank powers the no-key demo mode and tests.
"""

TOPIC_CONCEPTS: dict[str, list[str]] = {
    "Java": [
        "HashMap internals and collision resolution",
        "JVM garbage collection and its generations",
        "ConcurrentHashMap versus synchronized collections",
        "the equals()/hashCode() contract",
        "String immutability and the string pool",
        "checked versus unchecked exceptions",
        "interfaces versus abstract classes",
        "generics and type erasure",
        "the Stream API and lazy evaluation",
        "the ExecutorService and thread pools",
        "volatile and the happens-before relationship",
        "class loading and the JIT compiler",
    ],
    "Python": [
        "the GIL and its impact on threading",
        "list, tuple and set internals",
        "dict implementation and hashing",
        "decorators",
        "generators and lazy iteration",
        "context managers",
        "asyncio and the event loop",
        "multiprocessing versus threading",
        "duck typing and abstract base classes",
        "reference counting and garbage collection",
        "comprehensions and their performance",
        "the method resolution order (MRO)",
    ],
    "C++": [
        "RAII and deterministic resource management",
        "smart pointers (unique_ptr, shared_ptr, weak_ptr)",
        "move semantics and rvalue references",
        "virtual functions and vtables",
        "templates and compile-time polymorphism",
        "the rule of five",
        "memory layout and alignment",
        "undefined behavior pitfalls",
        "STL container performance guarantees",
        "const correctness",
        "std::atomic and the C++ memory model",
        "exception safety guarantees",
    ],
    "JavaScript": [
        "the event loop and the microtask queue",
        "closures",
        "prototypal inheritance",
        "promises and async/await",
        "hoisting and the temporal dead zone",
        "the rules of `this` binding",
        "ES modules versus CommonJS",
        "memory leaks in long-lived pages",
        "debouncing and throttling",
        "immutability patterns and structural sharing",
        "the browser rendering pipeline",
        "type coercion and equality rules",
    ],
    "Spring Boot": [
        "dependency injection and the bean lifecycle",
        "auto-configuration and starters",
        "@Transactional and its proxy mechanics",
        "Spring Data JPA and the N+1 query problem",
        "exception handling with @ControllerAdvice",
        "the Spring Security filter chain",
        "Actuator and production monitoring",
        "profiles and externalized configuration",
        "the caching abstraction",
        "async processing with @Async",
        "@SpringBootTest versus slice tests",
        "circular dependencies between beans",
    ],
    "React": [
        "the virtual DOM and reconciliation",
        "useEffect dependencies and cleanup",
        "lifting state versus context",
        "memoization with useMemo, useCallback and React.memo",
        "keys in rendered lists",
        "controlled versus uncontrolled components",
        "custom hooks",
        "Suspense and code splitting",
        "state-management trade-offs (Redux vs context vs local)",
        "diagnosing unnecessary re-renders",
        "error boundaries",
        "server-side rendering and hydration",
    ],
    "Node.js": [
        "the event loop phases and libuv",
        "streams and backpressure",
        "the cluster module and horizontal scaling",
        "error handling in async code",
        "module resolution",
        "worker threads versus child processes",
        "the Express middleware pattern",
        "memory leaks and heap snapshots",
        "non-blocking I/O",
        "graceful shutdown and process signals",
        "npm dependency security",
        "streaming versus buffering file handling",
    ],
    "MongoDB": [
        "document modeling versus relational normalization",
        "indexes and the query planner",
        "the aggregation pipeline",
        "replica sets and elections",
        "sharding and shard-key selection",
        "write concerns and read preferences",
        "multi-document transactions and their cost",
        "schema validation",
        "TTL and capped collections",
        "covered queries",
        "change streams and the oplog",
        "embedding versus referencing documents",
    ],
    "SQL": [
        "index types and when the planner uses them",
        "JOIN algorithms (nested loop, hash, merge)",
        "transaction isolation levels",
        "normalization versus denormalization",
        "reading and optimizing a query plan",
        "window functions",
        "GROUP BY and HAVING semantics",
        "NULL handling pitfalls",
        "locking and deadlocks",
        "CTEs and recursive queries",
        "table partitioning strategies",
        "ACID guarantees",
    ],
    "AWS": [
        "EC2 versus Lambda versus Fargate trade-offs",
        "S3 storage classes and consistency",
        "IAM roles and least-privilege policies",
        "VPC networking and security groups",
        "RDS versus DynamoDB selection",
        "SQS versus SNS versus EventBridge",
        "CloudFront and edge caching",
        "auto-scaling policies",
        "CloudWatch alarms and observability",
        "cost optimization tactics",
        "multi-region failover design",
        "KMS and encryption at rest",
    ],
    "Docker": [
        "images, containers and layers",
        "multi-stage builds",
        "container networking modes",
        "volumes and persistent data",
        "the build cache",
        "CPU and memory limits",
        "ENTRYPOINT versus CMD",
        "image vulnerability scanning",
        "Docker Compose versus Kubernetes",
        "namespaces and cgroups isolation",
        "minimizing image size",
        "health checks and restart policies",
    ],
    "CI/CD": [
        "pipeline stages and fail-fast ordering",
        "blue-green versus canary deployment",
        "trunk-based development versus gitflow",
        "automated testing gates",
        "artifact versioning and rollbacks",
        "secrets management in pipelines",
        "infrastructure as code",
        "build caching and pipeline speed",
        "feature flags",
        "post-deploy health verification",
        "monorepo versus polyrepo pipelines",
        "database migrations during deployment",
    ],
    "Operating Systems": [
        "processes versus threads",
        "virtual memory and paging",
        "context switching costs",
        "deadlock conditions and prevention",
        "CPU scheduling algorithms",
        "system calls and user/kernel mode",
        "file system journaling",
        "memory-mapped files",
        "interrupts and their handling",
        "inter-process communication mechanisms",
        "copy-on-write",
        "thrashing and the working-set model",
    ],
    "Networking": [
        "TCP versus UDP",
        "the TCP three-way handshake and teardown",
        "the TLS handshake and certificates",
        "the DNS resolution chain",
        "HTTP/1.1 versus HTTP/2 versus HTTP/3",
        "NAT and port forwarding",
        "L4 versus L7 load balancing",
        "CDNs and cache headers",
        "websockets versus long polling",
        "TCP congestion control",
        "subnetting and CIDR",
        "latency versus bandwidth trade-offs",
    ],
    "OOP": [
        "encapsulation and information hiding",
        "inheritance versus composition",
        "runtime versus compile-time polymorphism",
        "the SOLID principles",
        "the factory and strategy patterns",
        "abstract classes versus interfaces",
        "coupling and cohesion",
        "the Liskov substitution principle in practice",
        "immutability and its benefits",
        "god objects and other code smells",
        "dependency inversion",
        "the observer pattern and event-driven design",
    ],
    "DBMS": [
        "B+ tree index internals",
        "buffer pool management",
        "write-ahead logging and crash recovery",
        "MVCC and snapshot isolation",
        "two-phase locking",
        "query optimization and table statistics",
        "hash joins versus sort-merge joins",
        "denormalization trade-offs",
        "stored procedures versus application logic",
        "connection pooling",
        "replication topologies",
        "the CAP theorem in practice",
    ],
    "System Design": [
        "distributed caching",
        "message queues and delivery guarantees",
        "rate-limiting algorithms",
        "consistent hashing",
        "leader election",
        "database sharding",
        "CQRS and event sourcing",
        "idempotency in APIs",
        "circuit breakers",
        "service discovery",
        "distributed tracing",
        "back-of-envelope capacity estimation",
    ],
    "LLD": [
        "modeling classes for a parking-lot system",
        "designing an elevator controller state machine",
        "the strategy pattern for extensible behavior",
        "designing a thread-safe rate limiter class",
        "singleton implementations and their pitfalls",
        "designing an LRU cache with eviction policies",
        "API contract design",
        "designing a notification service",
        "error-handling hierarchies",
        "designing for testability and mocking seams",
        "designing a splitwise-style expense sharer",
        "designing a chess game's object model",
    ],
    "HLD": [
        "capacity estimation",
        "load balancer placement and health checks",
        "caching layers and invalidation strategy",
        "database replication and failover",
        "decomposing a monolith into microservices",
        "API gateway responsibilities",
        "asynchronous processing pipelines",
        "storage selection (blob vs relational vs NoSQL)",
        "multi-region architecture",
        "designing the observability stack",
        "queue-based load leveling",
        "cross-service data consistency",
    ],
    "Data Structures & Algorithms": [
        "hash tables and collision handling",
        "binary search trees and self-balancing",
        "heaps and priority queues",
        "BFS versus DFS graph traversals",
        "dynamic programming state design",
        "two-pointer techniques",
        "sliding-window patterns",
        "union-find (disjoint sets)",
        "tries and prefix search",
        "topological sorting",
        "greedy choices versus dynamic programming",
        "amortized time-space complexity analysis",
    ],
}

_TEMPLATES: dict[str, list[str]] = {
    "easy": [
        "Let's start with fundamentals: explain {c} in simple terms — what problem does it solve?",
        "What is {c}? Walk me through a basic example of it in practice.",
        "When would you reach for {c} in a real project? Give a concrete situation.",
        "Imagine explaining {c} to a junior engineer on their first week. How would you put it?",
        "What are the most common mistakes engineers make with {c}?",
    ],
    "medium": [
        "Compare {c} with its closest alternative — when does each one win?",
        "Walk me through how {c} actually works under the hood.",
        "You're reviewing a pull request that misuses {c}. What exactly are you checking for?",
        "How would you write meaningful tests for code that depends on {c}?",
        "What are the performance characteristics of {c}, and where do they bite in production?",
    ],
    "hard": [
        "Describe a scenario where {c} becomes the bottleneck of a system — how do you detect it and what's your fix?",
        "Production is failing intermittently and you suspect {c} is involved. Debug it for me, step by step.",
        "How would you implement a simplified version of {c} from scratch? Sketch the core design.",
        "Argue against using {c}: when is it the wrong choice, and what would you use instead?",
        "Your load just grew 100x. How does {c} behave now, what breaks first, and how do you redesign around it?",
    ],
}

_FALLBACK_TOPIC = "Data Structures & Algorithms"

# Prime-stride walk so consecutive questions hit different concepts.
_CONCEPT_STRIDE = 7


def questions_per_topic_difficulty(topic: str) -> int:
    concepts = TOPIC_CONCEPTS.get(topic, TOPIC_CONCEPTS[_FALLBACK_TOPIC])
    return len(concepts) * len(_TEMPLATES["easy"])


def get_question(topic: str, difficulty: str, index: int) -> str:
    """Deterministic, non-repeating (within 60 turns) topic question."""
    concepts = TOPIC_CONCEPTS.get(topic, TOPIC_CONCEPTS[_FALLBACK_TOPIC])
    templates = _TEMPLATES.get(difficulty, _TEMPLATES["medium"])
    concept = concepts[(index * _CONCEPT_STRIDE + 3) % len(concepts)]
    template = templates[index % len(templates)]
    return template.format(c=concept)
